name: clean_arch_project
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'


dependencies:
  # Functional Programming
  dartz: ^0.10.1
  # Remote API client
  dio: ^4.0.6
  # Local Memory Storage
  hive: ^2.0.4
  # Secure Storage
  flutter_secure_storage: ^6.0.0
  # Environment Variables
  flutter_config: ^2.0.0
  # Object comparable
  equatable: ^2.0.5
  # Modular organization
  flutter_modular: ^5.0.3
  # Dependecies injector
  get_it: ^7.6.0
  #Dson adapter
  dson_adapter: ^1.2.0+2
  # State management
  mobx: ^2.1.4
  #connectivity
  connectivity_plus: ^3.0.6
  flutter_mobx: ^2.0.6+1
  sizer: ^2.0.15
  flutter_native_splash: ^2.2.9
  path_provider: ^2.0.10
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
# Sort imports by scope - flutter pub run import_sorter:main
  import_sorter: ^4.6.0
  # Code generator - flutter pub run build_runner build
  build_runner: ^2.1.11
  # Mock dependencies
  mockito: ^5.3.0
  # Mobx code generator
  mobx_codegen: ^2.0.7
  # Flutter modular tests
  modular_test: ^2.0.0
  # Mocking Dio Adapter
  http_mock_adapter: ^0.3.2
  flutter_test:
    sdk: flutter
  
  
  flutter_lints: ^2.0.0
  
flutter: 
  
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
